routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true, 'reset' => true, 'confirm' => true]);

Route::where(['id' => '[0-9]+'])
    ->group(function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('search/', 'SearchController@index')->name('search');
        Route::namespace('Checkout')
            ->prefix('cart')
            ->group(function () {
                Route::get('', 'CartController@index')->name('cart');
                Route::get('items/', 'CartController@cartItems')->name('cart.items');
                Route::post('add/', 'CartController@addToCart')->name('cart.add');
                Route::delete('remove/', 'CartController@deleteItemCart')->name('cart.delete');
            });
        Route::namespace('Checkout')
            ->middleware('auth')
            ->prefix('checkout')
            ->group(function () {
                Route::get('', 'CheckoutController@index')->name('checkout');
            });
        Route::prefix('news')
            ->name('news')
            ->group(function () {
                Route::get('', 'NewsController@index');
                Route::get('/{id}/{slug}', 'NewsController@article')->name('.article');
            });
        Route::get('artistes/', 'ArtistesController@index')->name('artistes');

        Route::post('brow-se/category', "BrowseController@setCategory")->name('browse-set-category');
        Route::get('brow-se/', "BrowseController@index")->name('browse-index');
        Route::prefix('brow-se')
            ->name('browse.')
            ->group(function () {
                Route::get('release', "BrowseController@release")->name('release');
                Route::get('popular', "BrowseController@popular")->name('popular');
                Route::get('stations', "BrowseController@stations")->name('stations');
                Route::get('albums', "BrowseController@albums")->name('albums');
                Route::get('playlists', "BrowseController@playlists")->name('playlists');
                Route::get('genres', "BrowseController@genres")->name('genres');
            });
        Route::get('genre/{name}', "BrowseController@genre")->name('genre');

        Route::get('station/{id}/{title}', "StationController@index")
            ->name('station');
        Route::get('album/{id}/{name}', 'AlbumController@index')
            ->name('album');
        Route::get('playlist/{id}/{name}', "PlaylistController@index")
            ->name('playlist');

        Route::post('like/album/action/{id}/', "AlbumController@likeAction")->name('likeAlbum');
        Route::post('like/music/action/{id}/', "StationController@likeAction")->name('likeMusic');
        Route::post('like/playlist/action/{id}/', "PlaylistController@likeAction")->name('likePlaylist');

        Route::post('playings/{id}', "StationController@playingMusic")->name('playingCount');

        Route::post('follow/user/action/{id}', "UserController@followAction")->name('followUser');
        Route::prefix('user/{id}/{name}')
            ->name('user')
            ->group(function () {
                Route::get('stations', "UserController@stations");
                Route::get('stations/template/items', "UserController@stationsTemplates")->name('.stationsTemplates');

                Route::get('albums', "UserController@albums")->name('.albums');
                Route::get('albums/template/items', "UserController@albumsTemplates")->name('.albumsTemplates');

                Route::get('playlists', "UserController@playlists")->name('.playlists');
                Route::get('playlists/template/items', "UserController@playlistsTemplates")->name('.playlistsTemplates');


                Route::get('followers', "UserController@followers")->name('.followers');
                Route::get('followers/template/items', "UserController@followersTemplates")->name('.followersTemplates');

                Route::middleware(['auth', 'UserOnAuthPages'])
                    ->group(function () {
                        // 
                        Route::get('following', "UserAuthController@following")->name('.following');
                        Route::get('following/template/items', "UserAuthController@followingTemplates")->name('.followingTemplates');

                        Route::get('purchase', "UserAuthController@purchase")->name('.purchase');

                        Route::get('profile', "UserAuthController@profile")->name('.profile');
                        Route::put('profile', "UserAuthController@profileModify")->name('.profileModify');

                        Route::get('upload', "UserAuthController@upload")->name('.upload');
                        Route::post('upload/artiste-request', "UserAuthController@artisteRequest")->name('.upload.artiste-request');
                        Route::post('upload/music-request', "UserAuthController@musicRequest")->name('.upload.music-request');

                        Route::get('desconnect', "UserAuthController@desconnect")->name('.desconnect');
                    });
            });
    });
Route::post('locale/', "ChangeLocaleController@change")->name('locale');

// Admin routes
Route::get('dash/', fn () => redirect(route('admin.login')));
Route::namespace('Admin\Auth')
    ->prefix('dash')
    ->name('admin.login')
    ->group(function () {
        Route::get('login/', "AdminLoginController@showLoginForm");
        Route::post('login/', "AdminLoginController@login");
    });

Route::namespace('Admin')
    ->prefix('dash')
    ->name('admin.')
    ->where(['id' => '[0-9]+'])
    ->middleware('auth:admin')
    ->group(function () {
        Route::post('logout/', "Auth\AdminLoginController@logout")->name('logout');
        Route::get('home/', "DashboardController@index")->name('home');
        Route::get('artist/', "Artist\HomeArtistController@recent")->name('artist');
        Route::namespace('Artist')
            ->prefix('artist')
            ->name('artist.')
            ->group(function () {
                Route::get('status/', 'HomeArtistController@status')->name('status');
                Route::get('request/', "HomeArtistController@request")->name('request');
                Route::patch('modify/', "HomeArtistController@modifyArtist")->name('modify');

                Route::get('view/{id}/', "ArtistProfilController@traffic")->name('profile');
                Route::prefix('view/{id}/')
                    ->name('profile.')
                    ->group(function () {
                        Route::get('music/', "ArtistProfilController@music")->name('music');
                        Route::get('profile/', "ArtistProfilController@profile")->name('profile');
                        Route::get('report/', "ArtistProfilController@report")->name('report');
                        Route::get('orders/', "ArtistProfilController@orders")->name('orders');
                        Route::get('settings/', "ArtistProfilController@settings")->name('settings');
                    });
            });


        Route::get('music-album/', "MusicAlbumController@musics")->name("music_album");
        Route::prefix('music-album')
            ->name('musics.')
            ->group(function () {
                Route::get('playlists/',  "MusicAlbumController@playlists")->name('playlists');
                Route::get('albums/',  "MusicAlbumController@albums")->name('albums');
                Route::get('music-request/',  "MusicAlbumController@musicRequest")->name('music-request');
                Route::patch('playlist/', "MusicAlbumController@modifyPlaylist")->name('playlist.modify');;
                Route::patch('music/', "MusicAlbumController@modifyMusic")->name('music.modify');
                Route::patch('album/', "MusicAlbumController@modifyAlbum")->name('album.modify');

                Route::namespace('Musics')
                    ->name('music.profile')
                    ->prefix('music/profil/{id}')
                    ->group(function () {
                        Route::get('', "MusicProfilController@home")->name('.home');
                        Route::get('settings/', "MusicProfilController@settings")->name('.settings');
                    });
                Route::prefix('album/profil/{id}')
                    ->namespace('Album')
                    ->name('album.profile')
                    ->group(function () {
                        Route::get('', "AlbumProfilController@home")->name('.home');
                        Route::get('report/', "AlbumProfilController@report")->name('.report');
                        Route::get('settings/', "AlbumProfilController@settings")->name('.settings');
                    });
                Route::namespace('Playlist')
                    ->name('playlist.profile')
                    ->prefix('playlist/profil/{id}')
                    ->group(function () {
                        Route::get('', "PlaylistProfilController@home")->name('.home');
                        Route::get('report/', "PlaylistProfilController@report")->name('.report');
                        Route::get('settings/', "PlaylistProfilController@settings")->name('.settings');
                    });
            });


        Route::prefix('client')
            ->name('client')
            ->namespace('Client')
            ->group(function () {
                Route::get('', "ClientController@index");
            });

        Route::prefix('purchase')
            ->name('purchase')
            ->namespace('Purchase')
            ->group(function () {

resources/views/album.blade.php
@extends('layouts.app')

@section('title', $album->_name() . ' | '. __('Album'))

@section('meta-tags')
<meta property="og:locale" content="{{ app()->getLocale() }}">
<meta property="og:type" content="album">
<meta property="og:title" content="{{ $album->_name() }}">
<meta property="og:description"
    content="{{  $album->description ?: __('A Congolese and other music sales resource') }} !">
<meta property="og:url" content="{{ request()->fullUrl() }}">
<meta property="og:site_name" content="{{ $app_name }}">
<meta property="og:image" content="{{ asset($album->_image()) }}">
<meta property="og:image:type" content="image/jpeg" />
@endsection

@section('content')
@include('layouts.navbar', ['dark' => true])
<div class="mb-5" data-controller="Album">
    <div class="station--user">
        <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel" data-interval="false">
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <div class="view" style="background-image: url({{ asset($album->_image()) }});">
                        <div class="mask rgba-black-light d-flex align-items-center">
                            <div class="container">
                                <header class="entry-header typewriter">
                                    <h1 class="entry-title" data-controller="Title">
                                        {{ $album->_name() }}</h1>
                                    <div class="entry-description">
                                        {{ $album->description }}
                                    </div>
                                    <div class="entry-meta">
                                        <span>
                                            <button class="btn-play" data-action="Album#playOrPause"
                                                data-target="Album.playBtn">
                                                play
                                            </button>
                                        </span>

                                        <button data-action="Album#like" data-target="Album.LikeEl"
                                            data-url-action="{{ route('likeAlbum', ['id' => $album->id]) }}"
                                            class="btn-like {{ $liked ? 'active': '' }}">
                                            @include('templates.svg.like')
                                            <span class="count">{{ $likesCount }}</span>
                                        </button>

                                        <button class="btn-like">
                                            <span class="svg-icon">
                                                <img alt="{{ $album->user->_name() }}"
                                                    src="{{ asset($album->user->_image()) }}"
                                                    class="avatar avatar-48 photo img-cover-full" />
                                            </span>
                                            <span class="author vcard">
                                                <a class="url fn n author--name" href="{{ $album->user->route() }}">
                                                    {{ $album->user->_name() }}
                                                </a>
                                            </span>
                                        </button>
                                    </div>

                                    <div class="entry-term">
                                        <span class="entry-tag">
                                            <span class="tag">
                                                @include('layouts.add-to-cart')
                                            </span>
                                        </span>
                                        <span class="entry-cat"><span class="albums"><a
                                                    href="{{ route('browse.albums') }}"
                                                    rel="tag">{{ __('Albums') }}</a></span></span>
                                        <span class="entry-cat">
                                            <span data-action="Album#like" data-target="Album.LikeEl" class="btn-like">
                                                @include('templates.svg.music-svg')
                                                <span class="count">{{ $album->musics->count() }}</span>
                                            </span>
                                        </span>
                                    </div>
                                </header>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script id="music-id" data-swup-reload-script data-ai="{{ $album->id }}">
        window.$music = [
            @foreach($musics as $music) {
                "name": "{{ $music->_title() }}"
                , "artist": "{{ $album->user->_name() }}"
                , "album": "{{ $music->album ? $music->album->_name() : '' }}"
                , "url": "{{ $music->adminPlayer() }}"
                , "cover_art_url": "{{ asset($music->_image()) }}"
            }
            , @endforeach
        ];

    </script>
    <div class="container mt-3">
        <div class="row">
            <div class="col-12 col-lg-4 player--station--user">
                @include('layouts.amplitudes', ['url' => request()->fullUrl(), 'title' => $album->_name()])
            </div>
            <div class="col-12 col-lg-1"></div>
            <div class="col-12 col-lg-7 mt-5">
                <section>
                    <div class="row">
                        <div class="col-12">
                            <h5>{{ __('Stations') }}</h5>
                            <div class="last-top block-loop-index mt-4" style="overflow-y: auto; max-height: 640px">
                                @include('layouts.items-sm', ['items' => $musics])
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <div class="mt-5">
            <h5>{{ __('More') }}</h5>
            <div class="row mt-4">
                @include('layouts.items-albums', ['items' => $othersAlbum])
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/artistes.blade.php
@extends('layouts.app')

@section('title', __('Artistes'))

@section('content')
@include('layouts.navbar')
<div data-controller="Artistes" class="container content-top">
    <div class="station--user">
        <div class="row mt-4">
            @include('layouts.items-artistes', ['items' => $artistes])
        </div>
    </div>

    <div class="text-center">
        <div class="paginate--stations">
            {{ $artistes->links() }}
        </div>
    </div>
</div>
@endsection

resources/views/browse.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.navbar')
<div data-controller="Browse" data-Browse-category-url="{{ route('browse-set-category') }}">
    @include('layouts.browse-nav', [
    'tabs' => [
    [ 'name' => __('New Release'), 'route' => route('browse.release')],
    [ 'name' => __('Popular'), 'route' => route('browse.popular') ],
    [ 'name' => __('Stations'), 'route' => route('browse.stations')],
    [ 'name' => __('Albums'), 'route' => route('browse.albums')],
    [ 'name' => __('Playlists'), 'route' => route('browse.playlists')],
    [ 'name' => __('Genres'), 'route' => route('browse.genres')],
    ]
    ])
    <div class="container">
        @yield('browse')
    </div>
</div>
@endsection

resources/views/cart.blade.php
@extends('layouts.app')

@section('title', __('Cart'))

@section('content')

@include('layouts.navbar')
<div class="container mb-5 content-top">
    <div class="adding--card">
        <header class="mb-4">
            <h1>{{ __('Cart') }}</h1>
        </header>
        <div data-controller="Checkout--Cart" data-Checkout--Cart-cart-items="{{ route('cart.items') }}"
            data-Checkout--Cart-cart-item-delete="{{ route('cart.delete') }}"
            data-Checkout--Cart-is-auth="{{ Auth::check() ? 1 : 0 }}" data-Checkout--Cart-login="{{ route('login') }}"
            data-Checkout--Cart-checkout="{{ route('checkout') }}">
            <div class="text-center" style="color: #999999">
                <h5>{{ __('Loading') }}...</h5>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/checkout.blade.php
@extends('layouts.app')

@section('title', __('Checkout'))

@section('content')

@include('layouts.navbar')
<div class="container mb-5 content-top">
    <div class="adding--card">
        <header class="mb-4">
            <h1>{{ __('Checkout') }}</h1>
        </header>
        <script data-swup-reload-script>
            window.authUser = @json(Auth::user())
        </script>
        <div data-controller="Checkout--Checkout" data-Checkout--Checkout-cart-items="{{ route('cart.items') }}">
            <div class="text-center" style="color: #999999">
                <h5>{{ __('Loading') }}...</h5>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('title', __('Amazing songs'))

@section('content')
<div data-controller="Home">
    <header>
        @include('layouts.navbar', ['dark' => true])
        <div class="bg-slide--container">
            <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel"
                data-interval="false">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
                    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="carousel-item active">
                        <div class="view" style="background-image: url({{ asset('/images/artistes/fally1-rv.jpg') }});">
                            <div class="mask rgba-black-light d-flex align-items-center">
                                <div class="container">
                                    <div class="text-white wow fadeIn">
                                        <div class="entry-header typewriter">
                                            <h1 class="entry-title" data-controller="Title">
                                                {{ __('Amazing songs') }}</h1>
                                        </div>
                                        <div class="entry-text">
                                            <p class="mb-4 home-text-desc">
                                                {{ __('The best resource for Congolese and other music') }}.
                                            </p>
                                        </div>
                                        <a href="{{ route('browse.release') }}"
                                            class="btn btn-success wp-block-button__link">{{ __('New Arrival') }}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="carousel-item">
                        <div class="view" style="background-image: url({{ asset('/images/artistes/koffi1-rv.jpg') }});">
                            <div class="mask rgba-black-light d-flex align-items-center">
                                <div class="container">
                                    <div class="text-white wow fadeIn">
                                        <div class="entry-header">
                                            <h2 class="entry-title">{{ __('Discover songs you’ll love') }}</h2>
                                        </div>
                                        <div class="entry-text">
                                            <p class="mb-4 home-text-desc">
                                                {{ __('Find the most popular artists and listen their music on BnB') }} ({{ $app_name }})
                                            </p>
                                        </div>
                                        <a href="{{ route('browse-index') }}"
                                            class="btn btn-primary wp-block-button__link">{{ __('Browse') }}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="view lozad" data-background-image="{{ asset('/images/artistes/lokua2.jpg') }}">
                            <div class="mask rgba-black-light d-flex align-items-center">
                                <div class="container">
                                    <div class="text-white wow fadeIn">
                                        <div class="entry-header">
                                            <h2 class="entry-title">{{ __('For any artist') }}</h2>
                                        </div>
                                        <div class="entry-text">
                                            <p class="mb-4 home-text-desc">
                                                {{ __('A platform for any artist and fan') }}
                                            </p>
                                        </div>
                                        <a href="{{ $artiste_url }}"
                                            class="btn btn-secondary wp-block-button__link">{{ __('Propose') }}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <main>
        <div class="container my-5">
            <div class="release-container">
                <h5>{{ __('Mundane') }}</h5>
                <div class="row mt-4">
                    @include('layouts.items', ['items' => $musics['mundane']])
                </div>
            </div>
        </div>
        <div class="bg-disp">
            <div class="container">
                <div class="release-container">
                    <h5>{{ __('Religious') }}</h5>
                    <div class="row mt-4">
                        @include('layouts.items', ['items' => $musics['christian']])
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row my-5">
                <div class="col-sm-12 col-md-6">
                    <h5><a href="{{ route('browse.popular') }}">{{ __('Top popular songs') }}</a></h5>
                    <div class="last-top block-loop-index mt-4">
                        @include('layouts.items-sm', ['items' => $musics['popular']])
                    </div>
                </div>
                <div class="col-sm-12 col-md-6">
                    <h5><a href="{{ route('news') }}">{{ __('News') }}</a></h5>
                    <div class="row">
                        @include('layouts.items-news', ['items' => $news])
                    </div>
                </div>
            </div>
        </div>
        <div class="bg-parallax">
            <div class="wp-block-cover lozad"
                data-background-image="{{ asset('images/simples/slider-01-1920x1080.jpg') }}">
                <div class="text-center" style="width: 65%;z-index: 1;color: #f8f9f9;">
                    <h1>{{ __('Are you an artist') }} ?</h1>
                    <a href="{{ $artiste_url }}" class="btn btn-secondary wp-block-button__link btn-success mt-5">
                        {{ __('Submit your songs') }}
                    </a>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

resources/views/playlist.blade.php
@extends('layouts.app')

@section('title', $playlist->_name() . ' | '. __('Playlist'))

@section('meta-tags')
<meta property="og:locale" content="{{ app()->getLocale() }}">
<meta property="og:type" content="playlist">
<meta property="og:title" content="{{ $playlist->_name() }}">
<meta property="og:description" content="{{ __('A Congolese and other music sales resource') }} !">
<meta property="og:url" content="{{ request()->fullUrl() }}">
<meta property="og:site_name" content="{{ $app_name }}">
@endsection

@section('content')
@include('layouts.navbar')
<div class="mb-5" data-controller="Playlist">
    <div class="container">
        <div class="playlist-user">
            <header class="entry-header typewriter">
                <h1 class="entry-title" data-controller="Title">
                    {{ $playlist->_name() }}
                </h1>
                <div class="entry-meta mt-4">
                    <div style="height: 40px;width:40px;display: inline-block;">
                        @include('templates.svg.playlist-svg')
                    </div>
                    <button data-action="Playlist#like" data-target="Playlist.LikeEl"
                        data-url-action="{{ route('likePlaylist', ['id' => $playlist->id]) }}"
                        class="btn-like {{ $liked ? 'active': '' }}">
                        @include('templates.svg.like')
                        <span class="count"> {{ $likesCount }}</span>
                    </button>
                    <span class="byline">
                        <span class="svg-icon">
                            <img alt="{{ $playlist->user->_name() }}" src="{{ asset($playlist->user->_image()) }}"
                                class="avatar avatar-48 photo img-cover-full" height="48" width="48">
                        </span>
                        <span class="author vcard">
                            <a class="url fn n author--name" href="{{ $playlist->user->route() }}">
                                {{ $playlist->user->_name() }}
                            </a>
                        </span>
                    </span>
                </div>
                <div class="entry-term mt-5">
                    <span class="entry-tag">
                        <span class="tag">
                            @include('layouts.add-to-cart')
                        </span>
                    </span>
                    <span class="entry-cat ml-3">
                        <span class="albums">
                            <a href="{{ route('browse.playlists') }}" rel="tag">{{ __('Playlists') }}</a>
                        </span>
                    </span>
                    <span class="entry-cat ml-3">
                        <span data-action="Album#like" data-target="Album.LikeEl" class="btn-like">
                            @include('templates.svg.music-svg')
                            <span>{{ $playlist->items->count() }}</span>
                        </span>
                    </span>
                </div>
            </header>
        </div>
    </div>
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-12 col-lg-4 mt-3">
                <h5>{{ __('Stations') }}</h5>
                <div class="last-top block-loop-index mt-4" style="overflow-y: auto; max-height: 640px">
                    @include('layouts.items-sm', ['items' => $musics])
                </div>
            </div>
            <div class="col-12 col-lg-1"></div>
            <div class="col-12 col-lg-7 mt-4">
                <section>
                    <div class="release-container">
                        <h5>{{ __('More Playlists') }}</h5>
                        <div class="row mt-4">
                            @include('layouts.items-playlists', ['items' => $othersPlaylist, 'col' => 'col-6 col-lg-3'])
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/search.blade.php
@extends('layouts.app')

@section('title', __("Search Results for"). " “".request('s')."”")

@section('content')
@include('layouts.navbar')
<div class="container mb-5 content-top" data-controller="Search">
    <div class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                @if ($result->empty > 0)
                @include('_search.result')
                @else
                @include('_search.empty')
                @endif
            </main>
        </div>
    </div>
</div>
@endsection