routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true, 'reset' => true, 'confirm' => true]);

Route::where(['id' => '[0-9]+'])
    ->group(function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::get('search/', 'SearchController@index')->name('search');
        Route::namespace('Checkout')
            ->prefix('cart')
            ->group(function () {
                Route::get('', 'CartController@index')->name('cart');
                Route::get('items/', 'CartController@cartItems')->name('cart.items');
                Route::post('add/', 'CartController@addToCart')->name('cart.add');
                Route::delete('remove/', 'CartController@deleteItemCart')->name('cart.delete');
            });
        Route::namespace('Checkout')
            ->middleware('auth')
            ->prefix('checkout')
            ->group(function () {
                Route::get('', 'CheckoutController@index')->name('checkout');
            });
        Route::prefix('news')
            ->name('news')
            ->group(function () {
                Route::get('', 'NewsController@index');
                Route::get('/{id}/{slug}', 'NewsController@article')->name('.article');
            });
        Route::get('artistes/', 'ArtistesController@index')->name('artistes');

        Route::post('brow-se/category', "BrowseController@setCategory")->name('browse-set-category');
        Route::get('brow-se/', "BrowseController@index")->name('browse-index');
        Route::prefix('brow-se')
            ->name('browse.')
            ->group(function () {
                Route::get('release', "BrowseController@release")->name('release');
                Route::get('popular', "BrowseController@popular")->name('popular');
                Route::get('stations', "BrowseController@stations")->name('stations');
                Route::get('albums', "BrowseController@albums")->name('albums');
                Route::get('playlists', "BrowseController@playlists")->name('playlists');
                Route::get('genres', "BrowseController@genres")->name('genres');
            });
        Route::get('genre/{name}', "BrowseController@genre")->name('genre');

        Route::get('station/{id}/{title}', "StationController@index")
            ->name('station');
        Route::get('album/{id}/{name}', 'AlbumController@index')
            ->name('album');
        Route::get('playlist/{id}/{name}', "PlaylistController@index")
            ->name('playlist');

        Route::post('like/album/action/{id}/', "AlbumController@likeAction")->name('likeAlbum');
        Route::post('like/music/action/{id}/', "StationController@likeAction")->name('likeMusic');
        Route::post('like/playlist/action/{id}/', "PlaylistController@likeAction")->name('likePlaylist');

        Route::post('playings/{id}', "StationController@playingMusic")->name('playingCount');

        Route::post('follow/user/action/{id}', "UserController@followAction")->name('followUser');
        Route::prefix('user/{id}/{name}')
            ->name('user')
            ->group(function () {
                Route::get('stations', "UserController@stations");
                Route::get('stations/template/items', "UserController@stationsTemplates")->name('.stationsTemplates');

                Route::get('albums', "UserController@albums")->name('.albums');
                Route::get('albums/template/items', "UserController@albumsTemplates")->name('.albumsTemplates');

                Route::get('playlists', "UserController@playlists")->name('.playlists');
                Route::get('playlists/template/items', "UserController@playlistsTemplates")->name('.playlistsTemplates');


                Route::get('followers', "UserController@followers")->name('.followers');
                Route::get('followers/template/items', "UserController@followersTemplates")->name('.followersTemplates');

                Route::middleware(['auth', 'UserOnAuthPages'])
                    ->group(function () {
                        // 
                        Route::get('following', "UserAuthController@following")->name('.following');
                        Route::get('following/template/items', "UserAuthController@followingTemplates")->name('.followingTemplates');

                        Route::get('purchase', "UserAuthController@purchase")->name('.purchase');

                        Route::get('profile', "UserAuthController@profile")->name('.profile');
                        Route::put('profile', "UserAuthController@profileModify")->name('.profileModify');

                        Route::get('upload', "UserAuthController@upload")->name('.upload');
                        Route::post('upload/artiste-request', "UserAuthController@artisteRequest")->name('.upload.artiste-request');
                        Route::post('upload/music-request', "UserAuthController@musicRequest")->name('.upload.music-request');

                        Route::get('desconnect', "UserAuthController@desconnect")->name('.desconnect');
                    });
            });
    });
Route::post('locale/', "ChangeLocaleController@change")->name('locale');

// Admin routes
Route::get('dash/', fn () => redirect(route('admin.login')));
Route::namespace('Admin\Auth')
    ->prefix('dash')
    ->name('admin.login')
    ->group(function () {
        Route::get('login/', "AdminLoginController@showLoginForm");
        Route::post('login/', "AdminLoginController@login");
    });

Route::namespace('Admin')
    ->prefix('dash')
    ->name('admin.')
    ->where(['id' => '[0-9]+'])
    ->middleware('auth:admin')
    ->group(function () {
        Route::post('logout/', "Auth\AdminLoginController@logout")->name('logout');
        Route::get('home/', "DashboardController@index")->name('home');
        Route::get('artist/', "Artist\HomeArtistController@recent")->name('artist');
        Route::namespace('Artist')
            ->prefix('artist')
            ->name('artist.')
            ->group(function () {
                Route::get('status/', 'HomeArtistController@status')->name('status');
                Route::get('request/', "HomeArtistController@request")->name('request');
                Route::patch('modify/', "HomeArtistController@modifyArtist")->name('modify');

                Route::get('view/{id}/', "ArtistProfilController@traffic")->name('profile');
                Route::prefix('view/{id}/')
                    ->name('profile.')
                    ->group(function () {
                        Route::get('music/', "ArtistProfilController@music")->name('music');
                        Route::get('profile/', "ArtistProfilController@profile")->name('profile');
                        Route::get('report/', "ArtistProfilController@report")->name('report');
                        Route::get('orders/', "ArtistProfilController@orders")->name('orders');
                        Route::get('settings/', "ArtistProfilController@settings")->name('settings');
                    });
            });


        Route::get('music-album/', "MusicAlbumController@musics")->name("music_album");
        Route::prefix('music-album')
            ->name('musics.')
            ->group(function () {
                Route::get('playlists/',  "MusicAlbumController@playlists")->name('playlists');
                Route::get('albums/',  "MusicAlbumController@albums")->name('albums');
                Route::get('music-request/',  "MusicAlbumController@musicRequest")->name('music-request');
                Route::patch('playlist/', "MusicAlbumController@modifyPlaylist")->name('playlist.modify');;
                Route::patch('music/', "MusicAlbumController@modifyMusic")->name('music.modify');
                Route::patch('album/', "MusicAlbumController@modifyAlbum")->name('album.modify');

                Route::namespace('Musics')
                    ->name('music.profile')
                    ->prefix('music/profil/{id}')
                    ->group(function () {
                        Route::get('', "MusicProfilController@home")->name('.home');
                        Route::get('settings/', "MusicProfilController@settings")->name('.settings');
                    });
                Route::prefix('album/profil/{id}')
                    ->namespace('Album')
                    ->name('album.profile')
                    ->group(function () {
                        Route::get('', "AlbumProfilController@home")->name('.home');
                        Route::get('report/', "AlbumProfilController@report")->name('.report');
                        Route::get('settings/', "AlbumProfilController@settings")->name('.settings');
                    });
                Route::namespace('Playlist')
                    ->name('playlist.profile')
                    ->prefix('playlist/profil/{id}')
                    ->group(function () {
                        Route::get('', "PlaylistProfilController@home")->name('.home');
                        Route::get('report/', "PlaylistProfilController@report")->name('.report');
                        Route::get('settings/', "PlaylistProfilController@settings")->name('.settings');
                    });
            });


        Route::prefix('client')
            ->name('client')
            ->namespace('Client')
            ->group(function () {
                Route::get('', "ClientController@index");
            });

        Route::prefix('purchase')
            ->name('purchase')
            ->namespace('Purchase')
            ->group(function () {

resources/views/admin/artist.blade.php
@extends('admin.layouts.admin')
@section('nav-title', __('Artists'))
@section('content')
<div class="container-fluid" data-controller="Artists" aria-live="polite">
    <div>
        <button class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#NewArtist">
            <i class="material-icons">add_circle</i>
            {{__('New')}}
        </button>
    </div>
    @include('admin.layouts.tabs', [
    'tabs' => [
    [ 'name' => __('Artistes'), 'route' => route('admin.artist')],
    [ 'name' => __('Status Inactif'), 'route' => route('admin.artist.status')],
    [ 'name' => __('Artiste Request'), 'route' => route('admin.artist.request')]
    ]
    ])
    @yield('artist-out')
    <div class="card">
        <div class="card-body">
            @yield('artist')
        </div>
    </div>
    @include('admin.artist.modals.NewArtist')
</div>
@endsection

resources/views/admin/client.blade.php
@extends('admin.layouts.admin')
@section('nav-title', __('Client'))

@section('content')
<div data-controller="Client" class="client" data-Client-get-clients="{{ route('admin.client.all') }}"
    data-Client-search-client="{{ route('admin.client.search') }}"
    data-Client-client-details="{{ route('admin.client.details') }}"
    data-Client-client-following="{{ route('admin.client.following') }}"
    data-Client-client-followers="{{ route('admin.client.followers') }}"
    data-Client-client-likes="{{ route('admin.client.likes') }}"
    data-Client-client-purchase="{{ route('admin.client.purchase') }}"
    data-Client-client-to-artiste="{{ route('admin.client.clientToArtist') }}">
    <div class="row justify-content-center">
        <spinning-dots style="
                    width:50px;
                    stroke-width:5px;
                    color: #68c3ff;" />
    </div>
</div>
@endsection

resources/views/admin/dash.blade.php
@extends('admin.layouts.admin')

@section('nav-title', __('Dashboard'))

@section('content')
<div class="container-fluid" data-controller="Dash">
    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-warning card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">art_track</i>
                    </div>
                    <p class="card-category">{{ __('Artistes') }}</p>
                    <h3 class="card-title">{{ $artistes }}</h3>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-success card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">supervised_user_circle</i>
                    </div>
                    <p class="card-category">{{ __('Clients') }}</p>
                    <h3 class="card-title">{{ $clients }}</h3>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-danger card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">album</i>
                    </div>
                    <p class="card-category">{{ __('Musics') }}</p>
                    <h3 class="card-title">{{ $musics }}</h3>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6">
            <div class="card card-stats">
                <div class="card-header card-header-info card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">
                            public
                        </i>
                    </div>
                    <p class="card-category">{{ __('Downloads') }}</p>
                    <h3 class="card-title">{{ $downloads }}</h3>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="card card-chart">
                <div class="card-header card-header-success">
                    <div class="ct-chart py-5" id="dailySalesChart"></div>
                </div>
                <div class="card-body">
                    <h4 class="card-title">{{ __('24h') }}</h4>
                    <p class="card-category"></p>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-chart">
                <div class="card-header card-header-warning">
                    <div class="ct-chart py-5" id="websiteViewsChart"></div>
                </div>
                <div class="card-body">
                    <h4 class="card-title">{{ __('Week') }}</h4>
                    <p class="card-category"></p>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-chart">
                <div class="card-header card-header-danger">
                    <div class="ct-chart py-5" id="completedTasksChart"></div>
                </div>
                <div class="card-body">
                    <h4 class="card-title">{{ __('Year') }}</h4>
                    <p class="card-category"></p>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/login.blade.php
@extends('admin.layouts.app-admin')

@section('app-content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6 col-12">
            <div class="card">
                <div class="card-body">
                    <form class="form-signin" method="POST" action="{{ route('admin.login') }}">
                        @csrf
                        <div class="text-center mb-4 mt-5">
                            <h1 class="h3 mb-3 font-weight-normal">{{ $app_name }}</h1>
                            <p>{{ __('Administration') }}</p>
                        </div>
        
                        <div class="form-label-group">
                            <input type="email" id="email" class="form-control @error('email') is-invalid @enderror"
                                name="email" value="{{ old('email') }}" placeholder="Email adresse" required autofocus>
                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
        
                        <div class="form-label-group">
                            <input type="password" id="password" name="password"
                                class="form-control @error('password') is-invalid @enderror" placeholder="Password" required>
                            @error('password')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">{{ __('Login') }}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/music_album.blade.php
@extends('admin.layouts.admin')
@section('nav-title', __('Musics'))

@section('content')
<div data-controller="Music-Album">
  <div class="container-fluid" aria-live="polite">
    <div>
      <button class="btn btn-secondary btn-sm" data-toggle="modal" data-target="#GeneralPrice">
        <i class="material-icons">add_circle</i>
        {{__('General Price')}}
      </button>
      <span class="mx-3">
        <b>$<span data-target="Music-Album.price">{{ $price }}</span></b>
      </span>
    </div>
    @include('admin.layouts.tabs', [
    'tabs' => [
    [ 'name' => __('Musics'), 'route' => route('admin.music_album')],
    [ 'name' => __('Albums'), 'route' => route('admin.musics.albums')],
    [ 'name' => __('Playlists'), 'route' => route('admin.musics.playlists')],
    [ 'name' => __('Music Request'), 'route' => route('admin.musics.music-request')]
    ]
    ])
    <div class="card">
      <div class="card-body">
        @yield('music-album')
      </div>
    </div>
  </div>


  <div class="modal fade" id="GeneralPrice" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myLargeModalLabel">{{ __('General Price, (Per Music)') }}</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <form data-action="Music-Album#generalPrice" enctype="multipart/form-data" method="POST"
          action="{{ route('admin.music-album.general-price', [], false) }}" autocomplete="off">
          <div class="modal-body">
            <div class="row ">
              <div class="card-body">
                <div class="form-group">
                  <label class="pure-material-textfield-outlined w-100">
                    <input name="price">
                    <span>{{ __('Price') }}</span>
                  </label>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-info">{{ __('Save') }}
              <div class="ripple-container"></div>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

@endsection

resources/views/admin/news.blade.php
@extends('admin.layouts.admin')
@section('nav-title', __('News'))

@section('content')
<div class="container-fluid" data-controller="News" aria-live="polite">
    @include('admin.layouts.tabs', [
    'tabs' => [
    [ 'name' => __('New article'), 'route' => route('admin.news')],
    [ 'name' => __('Articles'), 'route' => route('admin.news.articles')],
    [ 'name' => __('Categories'), 'route' => route('admin.news.categories')]
    ]
    ])
    <div class="card">
        <div class="card-body news">
            @yield('news-content')
        </div>
    </div>
</div>
@endsection

resources/views/admin/purchase.blade.php
@extends('admin.layouts.admin')
@section('nav-title', __('Purchase'))
@section('content')
<div class="container-fluid" data-controller="Artists" aria-live="polite">
    @include('admin.layouts.tabs', [
    'tabs' => [
    [ 'name' => __('Purchases'), 'route' => route('admin.purchase')],
    ]
    ])
    @yield('artist-out')
    <div class="card">
        <div class="card-body">
            @yield('purchase-content')
        </div>
    </div>
</div>
@endsection