routes/web.php
        Route::get('search/', 'SearchController@index')->name('search');
        Route::namespace('Checkout')
            ->prefix('cart')
            ->group(function () {
                Route::get('', 'CartController@index')->name('cart');
                Route::get('items/', 'CartController@cartItems')->name('cart.items');
                Route::post('add/', 'CartController@addToCart')->name('cart.add');
                Route::delete('remove/', 'CartController@deleteItemCart')->name('cart.delete');
            });
        Route::namespace('Checkout')
            ->middleware('auth')
            ->prefix('checkout')
            ->group(function () {
                Route::get('', 'CheckoutController@index')->name('checkout');
            });
        Route::prefix('news')
            ->name('news')
            ->group(function () {
                Route::get('', 'NewsController@index');
                Route::get('/{id}/{slug}', 'NewsController@article')->name('.article');
            });
        Route::get('artistes/', 'ArtistesController@index')->name('artistes');

        Route::post('brow-se/category', "BrowseController@setCategory")->name('browse-set-category');
        Route::get('brow-se/', "BrowseController@index")->name('browse-index');
        Route::prefix('brow-se')
            ->name('browse.')
            ->group(function () {
                Route::get('release', "BrowseController@release")->name('release');
                Route::get('popular', "BrowseController@popular")->name('popular');
                Route::get('stations', "BrowseController@stations")->name('stations');
                Route::get('albums', "BrowseController@albums")->name('albums');
                Route::get('playlists', "BrowseController@playlists")->name('playlists');
                Route::get('genres', "BrowseController@genres")->name('genres');
            });
        Route::get('genre/{name}', "BrowseController@genre")->name('genre');

        Route::get('station/{id}/{title}', "StationController@index")
            ->name('station');
        Route::get('album/{id}/{name}', 'AlbumController@index')
            ->name('album');
        Route::get('playlist/{id}/{name}', "PlaylistController@index")
            ->name('playlist');

        Route::post('like/album/action/{id}/', "AlbumController@likeAction")->name('likeAlbum');
        Route::post('like/music/action/{id}/', "StationController@likeAction")->name('likeMusic');
        Route::post('like/playlist/action/{id}/', "PlaylistController@likeAction")->name('likePlaylist');

        Route::post('playings/{id}', "StationController@playingMusic")->name('playingCount');

        Route::post('follow/user/action/{id}', "UserController@followAction")->name('followUser');
        Route::prefix('user/{id}/{name}')
            ->name('user')
            ->group(function () {
                Route::get('stations', "UserController@stations");
                Route::get('stations/template/items', "UserController@stationsTemplates")->name('.stationsTemplates');

                Route::get('albums', "UserController@albums")->name('.albums');
                Route::get('albums/template/items', "UserController@albumsTemplates")->name('.albumsTemplates');

                Route::get('playlists', "UserController@playlists")->name('.playlists');
                Route::get('playlists/template/items', "UserController@playlistsTemplates")->name('.playlistsTemplates');


                Route::get('followers', "UserController@followers")->name('.followers');
                Route::get('followers/template/items', "UserController@followersTemplates")->name('.followersTemplates');

                Route::middleware(['auth', 'UserOnAuthPages'])
                    ->group(function () {
                        // 
                        Route::get('following', "UserAuthController@following")->name('.following');
                        Route::get('following/template/items', "UserAuthController@followingTemplates")->name('.followingTemplates');

                        Route::get('purchase', "UserAuthController@purchase")->name('.purchase');

                        Route::get('profile', "UserAuthController@profile")->name('.profile');
                        Route::put('profile', "UserAuthController@profileModify")->name('.profileModify');

                        Route::get('upload', "UserAuthController@upload")->name('.upload');
                        Route::post('upload/artiste-request', "UserAuthController@artisteRequest")->name('.upload.artiste-request');
                        Route::post('upload/music-request', "UserAuthController@musicRequest")->name('.upload.music-request');

                        Route::get('desconnect', "UserAuthController@desconnect")->name('.desconnect');
                    });
            });
    });
Route::post('locale/', "ChangeLocaleController@change")->name('locale');

// Admin routes
Route::get('dash/', fn () => redirect(route('admin.login')));
Route::namespace('Admin\Auth')
    ->prefix('dash')
    ->name('admin.login')
    ->group(function () {
        Route::get('login/', "AdminLoginController@showLoginForm");
        Route::post('login/', "AdminLoginController@login");
    });

Route::namespace('Admin')
    ->prefix('dash')
    ->name('admin.')
    ->where(['id' => '[0-9]+'])
    ->middleware('auth:admin')
    ->group(function () {
        Route::post('logout/', "Auth\AdminLoginController@logout")->name('logout');
        Route::get('home/', "DashboardController@index")->name('home');
        Route::get('artist/', "Artist\HomeArtistController@recent")->name('artist');
        Route::namespace('Artist')
            ->prefix('artist')
            ->name('artist.')
            ->group(function () {
                Route::get('status/', 'HomeArtistController@status')->name('status');
                Route::get('request/', "HomeArtistController@request")->name('request');
                Route::patch('modify/', "HomeArtistController@modifyArtist")->name('modify');

                Route::get('view/{id}/', "ArtistProfilController@traffic")->name('profile');
                Route::prefix('view/{id}/')
                    ->name('profile.')
                    ->group(function () {
                        Route::get('music/', "ArtistProfilController@music")->name('music');
                        Route::get('profile/', "ArtistProfilController@profile")->name('profile');
                        Route::get('report/', "ArtistProfilController@report")->name('report');
                        Route::get('orders/', "ArtistProfilController@orders")->name('orders');
                        Route::get('settings/', "ArtistProfilController@settings")->name('settings');
                    });
            });


        Route::get('music-album/', "MusicAlbumController@musics")->name("music_album");
        Route::prefix('music-album')
            ->name('musics.')
            ->group(function () {
                Route::get('playlists/',  "MusicAlbumController@playlists")->name('playlists');
                Route::get('albums/',  "MusicAlbumController@albums")->name('albums');
                Route::get('music-request/',  "MusicAlbumController@musicRequest")->name('music-request');
                Route::patch('playlist/', "MusicAlbumController@modifyPlaylist")->name('playlist.modify');;
                Route::patch('music/', "MusicAlbumController@modifyMusic")->name('music.modify');
                Route::patch('album/', "MusicAlbumController@modifyAlbum")->name('album.modify');

                Route::namespace('Musics')
                    ->name('music.profile')
                    ->prefix('music/profil/{id}')
                    ->group(function () {
                        Route::get('', "MusicProfilController@home")->name('.home');
                        Route::get('settings/', "MusicProfilController@settings")->name('.settings');
                    });
                Route::prefix('album/profil/{id}')
                    ->namespace('Album')
                    ->name('album.profile')
                    ->group(function () {
                        Route::get('', "AlbumProfilController@home")->name('.home');
                        Route::get('report/', "AlbumProfilController@report")->name('.report');
                        Route::get('settings/', "AlbumProfilController@settings")->name('.settings');
                    });
                Route::namespace('Playlist')
                    ->name('playlist.profile')
                    ->prefix('playlist/profil/{id}')
                    ->group(function () {
                        Route::get('', "PlaylistProfilController@home")->name('.home');
                        Route::get('report/', "PlaylistProfilController@report")->name('.report');
                        Route::get('settings/', "PlaylistProfilController@settings")->name('.settings');
                    });
            });


        Route::prefix('client')
            ->name('client')
            ->namespace('Client')
            ->group(function () {
                Route::get('', "ClientController@index");
            });

        Route::prefix('purchase')
            ->name('purchase')
            ->namespace('Purchase')
            ->group(function () {
                Route::get('', "PurchaseController@index");
            });

        Route::get('events/', "EventController@index")->name('event');
        Route::prefix('news')
            ->name('news')
            ->group(function () {
                Route::get('', "NewsController@newArticle");
                Route::get('articles/', "NewsController@articles")->name('.articles');
                Route::patch('article/', "NewsController@modifyArticle")->name('.article.modify');
                Route::get('categories/', "NewsController@categories")->name('.categories');
                Route::delete('category/', "NewsController@delCategory")->name('.category.delete');
            });

app/Http/Controllers/Admin/MusicAlbumController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Repository\AlbumRepository;
use App\Repository\GeneralPriceRepository;
use App\Repository\MusicRepository;
use App\Repository\PlaylistRepository;
use App\Statics\Category;
use App\Statics\File;
use App\Statics\Genres;
use Illuminate\Http\Request;

class MusicAlbumController extends Controller
{

    /**
     * @var AlbumRepository
     */
    private AlbumRepository $album;

    /**
     * @var MusicRepository
     */
    private MusicRepository $music;

    /**
     * @var PlaylistRepository
     */
    private PlaylistRepository $playlist;

    /**
     * @var array
     */
    private array $status = [
        'actif' => true,
        'inactif' => false
    ];


    /**
     * @return bool|string
     */
    private function status()
    {
        return array_key_exists(request('f'), $this->status) ? $this->status[request('f')] : '';
    }

    /**
     * @param AlbumRepository $album
     * @param MusicRepository $music
     * @param PlaylistRepository $playlist
     */
    public function __construct(AlbumRepository $album, MusicRepository $music, PlaylistRepository $playlist)
    {
        $this->album = $album;
        $this->music = $music;
        $this->playlist = $playlist;
    }

    /**
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function musics()
    {
        $musics = $this->music->getMusicsByFilter(12, request('q', ''), $this->status());
        return view('admin.music-album.musics', compact('musics'));
    }

    /**
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function albums()
    {
        $albums = $this->album->getAlbumsByFilter(12, request('q', ''), $this->status());
        return view('admin.music-album.albums', compact('albums'));
    }

    /**
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function playlists()
    {
        $playlists = $this->playlist->getPlaylistsByFilter(12, request('q', ''), $this->status());
        return view('admin.music-album.playlists', compact('playlists'));
    }
    /**
     * Show the application.
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function musicRequest()
    {
        return view('admin.music-album.music-request');
    }

    /**
     * @return \Illuminate\Http\RedirectResponse
     */
    public function modifyMusic()
    {
        $redirect = request('redirect');
        $id = request('id');
        $music = $this->music->findMusicOrFail($id);
        $music->active = !$music->active;
        $music->save();
        return redirect($redirect);
    }

    /**
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function modifyAlbum()
    {
        $redirect = request('redirect');
        $id = request('id');
        $album = $this->album->findAlbumOrFail($id);
        $album->active = !$album->active;
        $album->save();
        return redirect($redirect);
    }

    /**
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function modifyPlaylist()
    {
        $redirect = request('redirect');
        $id = request('id');
        $playlist = $this->playlist->findPlaylistOrFail($id);
        $playlist->active = !$playlist->active;
        $playlist->save();
        return redirect($redirect);
    }

    /**
     * @param Request $request
     * @param GeneralPriceRepository $rp
     * 
     * @return array
     */
    public function putGeneralPrice(Request $request, GeneralPriceRepository $rp)
    {
        $request->validate([
            'price' => ['required', 'numeric', 'min:0.1']
        ]);
        $price = $request->get('price');
        $rp->setActivePrice($price);
        return ['message' => trans('Saved'), 'price' => $price];
    }
}

resources/views/admin/music-album/albums.blade.php
@extends('admin.music_album')

@section('music-album')
@include('admin.layouts.search', ['filter' => true])
{{ $albums->links() }}
<table class="table">
    <thead>
        <tr>
            <th class="text-center">#</th>
            <th>{{ __('Image') }}</th>
            <th>{{ __('Title') }}</th>
            <th>{{ __('Author') }}</th>
            <th>{{ __('Price') }}</th>
            <th>{{ __('Status') }}</th>
            <th>{{ __('Recorded on') }}</th>
            <th>{{ __('Musics') }}</th>
            <th>{{ __('Actions') }}</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($albums as $album)
        <tr>
            <td class="text-center">{{ $album->id }}</td>
            <td>
                <div class="img-container">
                    <img class="img-cover-full" src="{{ asset($album->_image()) }}" alt="{{ $album->_name() }}"
                        rel="nofollow">
                </div>
            </td>
            <td><a href="{{ $album->adminRoute() }}">{{ $album->_name() }}</a></td>
            <td><a href="{{ $album->user->adminRoute() }}">{{ $album->user->_name() }}</a></td>
            <td>${{ $album->_price() }}</td>
            @if ($album->active)
            <th class="text-success">{{ __('Actif') }}</th>
            @else
            <th class="text-danger">{{ __('Inactif') }}</th>
            @endif
            <td>{{ $album->created_at }}</td>
            <td>{{ $album->musics->count() }}</td>
            <td class="td-actions">
                <a href="{{ $album->adminRoute() }}" class="btn btn-info">
                    <i class="material-icons">link</i>
                </a>
                <button class="btn {{ $album->active ? 'btn-danger': 'btn-primary' }}" onclick="event.preventDefault();
                    document.getElementById('delete-album-form-{{ $album->id }}').submit();">
                    <i class="material-icons">{{ $album->active ? 'close': 'done' }}</i>
                </button>
                <form id="delete-album-form-{{ $album->id }}"
                    action="{{ route('admin.musics.album.modify', ['id' => $album->id, 'redirect' => request()->fullUrl()]) }}"
                    method="POST" style="display: none;">
                    @method('PATCH')
                    @csrf
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
<div class="text-center">
    @empty($albums->items())
    <span class="text-warning">{{ __('No Items found') }}</span>
    @endempty
</div>
@endsection

resources/views/admin/music-album/music-request.blade.php
@extends('admin.music_album')

@section('music-album')
<div class="text-center">
    <h5>{{ __('Coming Soon') }}</h5>
</div>
@endsection

resources/views/admin/music-album/musics.blade.php
@extends('admin.music_album')

@section('music-album')
@include('admin.layouts.search', ['filter' => true])
{{ $musics->links() }}
<table class="table">
    <thead>
        <tr>
            <th class="text-center">#</th>
            <th>{{ __('Image') }}</th>
            <th>{{ __('Title') }}</th>
            <th>{{ __('Author') }}</th>
            <th>{{ __('Price') }}</th>
            <th>{{ __('Status') }}</th>
            <th>{{ __('Recorded on') }}</th>
            <th>{{ __('Album') }}</th>
            <th>{{ __('Actions') }}</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($musics as $music)
        <tr>
            <td class="text-center">{{ $music->id }}</td>
            <td>
                <div class="img-container">
                    <img class="img-cover-full" src="{{ asset($music->_image()) }}" alt="{{ $music->_title() }}"
                        rel="nofollow">
                </div>
            </td>
            <td>
                <a href="{{ $music->adminRoute() }}">
                    {{ $music->_title() }}
                </a>
            </td>
            <td>
                <a href="{{ $music->user->adminRoute() }}">
                    {{ $music->user->_name() }}
                </a>
            </td>
            <td>${{ $music->_price() }}</td>
            @if ($music->active)
            <th class="text-success">{{ __('Actif') }}</th>
            @else
            <th class="text-danger">{{ __('Inactif') }}</th>
            @endif
            <td>{{ $music->created_at }}</td>
            @if ($music->album)
            <td>
                <a href="{{ $music->album->adminRoute() }}">{{ $music->album->_name() }}</a>
            </td>
            @else
            <td>--</td>
            @endif

            <td class="td-actions">
                <a href="{{ $music->adminRoute() }}" class="btn btn-info">
                    <i class="material-icons">link</i>
                </a>
                <button class="btn {{ $music->active ? 'btn-danger': 'btn-primary' }}" onclick="event.preventDefault();
                    document.getElementById('delete-music-form-{{ $music->id }}').submit();">
                    <i class="material-icons">{{ $music->active ? 'close': 'done' }}</i>
                </button>
                <form id="delete-music-form-{{ $music->id }}"
                    action="{{ route('admin.musics.music.modify', ['id' => $music->id, 'redirect' => request()->fullUrl()]) }}"
                    method="POST" style="display: none;">
                    @method('PATCH')
                    @csrf
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
<div class="text-center">
    @empty($musics->items())
    <span class="text-warning">{{ __('No Items found') }}</span>
    @endempty
</div>
@endsection

resources/views/admin/music-album/playlists.blade.php
@extends('admin.music_album')

@section('music-album')
@include('admin.layouts.search', ['filter' => true])
{{ $playlists->links() }}
<table class="table">
    <thead>
        <tr>
            <th class="text-center">#</th>
            <th>{{ __('Title') }}</th>
            <th>{{ __('Author') }}</th>
            <th>{{ __('Price') }}</th>
            <th>{{ __('Status') }}</th>
            <th>{{ __('Recorded on') }}</th>
            <th>{{ __('Musics') }}</th>
            <th>{{ __('Actions') }}</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($playlists as $playlist)
        <tr>
            <td class="text-center">{{ $playlist->id }}</td>
            <td><a href="{{ $playlist->adminRoute() }}">{{ $playlist->_name() }}</a></td>
            <td><a href="{{ $playlist->user->adminRoute() }}">{{ $playlist->user->_name() }}</a></td>
            <td>${{ $playlist->_price() }}</td>
            @if ($playlist->active)
            <th class="text-success">{{ __('Actif') }}</th>
            @else
            <th class="text-danger">{{ __('Inactif') }}</th>
            @endif
            <td>{{ $playlist->created_at }}</td>
            <td>{{ $playlist->items->count() }}</td>
            <td class="td-actions">
                <a href="{{ $playlist->adminRoute() }}" class="btn btn-info">
                    <i class="material-icons">link</i>
                </a>
                <button class="btn {{ $playlist->active ? 'btn-danger': 'btn-primary' }}" onclick="event.preventDefault();
                    document.getElementById('delete-playlist-form-{{ $playlist->id }}').submit();">
                    <i class="material-icons">{{ $playlist->active ? 'close': 'done' }}</i>
                </button>
                <form id="delete-playlist-form-{{ $playlist->id }}"
                    action="{{ route('admin.musics.playlist.modify', ['id' => $playlist->id, 'redirect' => request()->fullUrl()]) }}"
                    method="POST" style="display: none;">
                    @method('PATCH')
                    @csrf
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
<div class="text-center">
    @empty($playlists->items())
    <span class="text-warning">{{ __('No Items found') }}</span>
    @endempty
</div>
@endsection

resources/views/admin/music-album/profile-album.blade.php
@extends('admin.layouts.admin')
@section('nav-title', __('Album').' | '.$album->name)
@section('content')
<div class="container-fluid" data-controller="album--Profile">
    <button type="button" class="btn btn-secondary btn-sm" onclick="history.back()">
        <i class="material-icons">chevron_left</i>
    </button>
    <div class="row">
        <div class="col-md-10 ml-auto mr-auto">
            <div class="card profil-card">
                <div class="raduis">
                    <div class="card-header card-header-danger card-icon-img shadow-dark-c"
                        style="background-image: url({{ asset($album->_image()) }});">
                        <span class="mask bg-gradient-default opacity-8"></span>
                        <div class="container-fluid d-flex align-items-center mt-5">
                            <div class="row">
                                <div class="col-12">
                                    <h5 class="display-4 text-white">{{ $album->_name() }}</h5>
                                </div>
                                <div class="col-lg-7 col-md-10">
                                    <p class="text-white mt-0 mb-3">{{ $album->description ?? '...' }}</p>
                                </div>
                                <div class="col-12 mb-1">
                                    <div class="user-links">
                                        <span>
                                            <a href="javascript:;">
                                                <i class="material-icons">favorite_outline</i>
                                                {{ $album->likes->count() }}
                                            </a>
                                        </span>
                                        <span>
                                            <a href="javascript:;">
                                                <i class="material-icons">cloud_download</i>
                                                {{ $album->downloads->count() }}
                                            </a>
                                        </span>
                                        <span>
                                            <a href="javascript:;">
                                                <i class="material-icons">shopping_basket</i>
                                                ${{ $album->orders->sum('total') }}
                                            </a>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <h5>{{ __('Artiste: ') }} 
                                        <a href="{{ $album->user->adminRoute() }}">
                                            {{ $album->user->_name() }}
                                        </a>
                                        {{ __('Price: ') }} ${{ $album->_price() }}
                                    </h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="tabs--dash">
                        @include('admin.layouts.tabs', [
                        'tabs' => [
                        [ 'name' => __('Music'). " (" .$album->musics->count(). ")", 'route' =>
                        route('admin.musics.album.profile.home', ['id' =>
                        $album->id]), 'icon' => 'library_music'],
                        [ 'name' => __('Report'), 'route' => route('admin.musics.album.profile.report', ['id' =>
                        $album->id]), 'icon' => 'report'],
                        [ 'name' => __('Settings'), 'route' => route('admin.musics.album.profile.settings', ['id' =>
                        $album->id]), 'icon' => 'settings'],
                        ]
                        ])
                    </div>
                    <div class="tab-content">
                        @yield('album-profile')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/music-album/profile-music.blade.php
@extends('admin.layouts.admin')
@section('nav-title', __('Music').' | '.$music->_title())
@section('content')
<div class="container-fluid" data-controller="music--Profile" data-music--Profile-audio="{{ $music->adminPlayer() }}">
    <button type="button" class="btn btn-secondary btn-sm" onclick="history.back()">
        <i class="material-icons">chevron_left</i>
    </button>
    <div class="row">
        <div class="col-md-10 ml-auto mr-auto">
            <div class="card profil-card">
                <div class="raduis">
                    <div class="card-header card-header-danger card-icon-img shadow-dark-c"
                        style="background-image: url({{ asset($music->_image()) }});">
                        <span class="mask bg-gradient-default opacity-8"></span>
                        <div class="container-fluid d-flex align-items-center mt-5">
                            <div class="row">
                                <div class="col-12">
                                    <h5 class="display-4 text-white">{{ $music->_title() }}</h5>
                                </div>
                                <div class="col-12 my-3" data-target="music--Profile.audio">
                                    <button class="btn btn-outline-light" data-play="{{ $music->adminPlayer() }}"
                                        type="button" title="Play">
                                        <div style="display:none">
                                            <audio preload="none" controls playsinline controlsList="nodownload">
                                                <source src="{{ $music->adminPlayer() }}" type="audio/mpeg">
                                            </audio>
                                        </div>
                                        <i class="material-icons" style="font-size: 19px;">play_circle_outline</i>
                                    </button>
                                </div>
                                <div class="col-12 mb-1">
                                    <div class="user-links">
                                        <span>
                                            <a href="javascript:;">
                                                <i class="material-icons">favorite_outline</i>
                                                {{ $music->likes->count() }}
                                            </a>
                                        </span>
                                        <span>
                                            <a href="javascript:;">
                                                <i class="material-icons">cloud_download</i>
                                                {{ $music->downloads->count() }}
                                            </a>
                                        </span>
                                        <span>
                                            <a href="javascript:;">
                                                <i class="material-icons">shopping_basket</i>
                                                {{ $music->orders->sum('total') }}
                                            </a>
                                        </span>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <h5>{{ __('Artiste: ') }} 
                                        <a href="{{ $music->user->adminRoute() }}">
                                            {{ $music->user->_name() }}
                                        </a>
                                        {{ __('Price: ') }} ${{ $music->_price() }}
                                    </h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body ">
                    <div class="tabs--dash">
                        @include('admin.layouts.tabs', [
                        'tabs' => [
                        [ 'name' => __('Report'), 'route' => route('admin.musics.music.profile.home', ['id' =>
                        $music->id]), 'icon' => 'report'],
                        [ 'name' => __('Settings'), 'route' => route('admin.musics.music.profile.settings', ['id' =>
                        $music->id]), 'icon' => 'settings'],
                        ]
                        ])
                    </div>
                    <div class="tab-content">
                        @yield('music-profile')
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection